name: Ingest
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt beautifulsoup4 lxml
      - name: Run ingestion
        run: python ingest.py
      - name: Archive database
        uses: actions/upload-artifact@v4
        with:
          name: news-db
          path: news.db

