name: Ingest
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt beautifulsoup4 lxml
      - name: Install GitHub CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gh
      - name: Download latest database
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set +e
          RUN_ID=$(gh run list --workflow ingest.yml --branch ${{ github.ref_name }} --status success -L 1 --json databaseId -q '.[0].databaseId' || echo "")
          if [ -n "$RUN_ID" ]; then
            gh run download "$RUN_ID" -n news-db || echo "No artifact to download"
            if [ -f news-db/news.db ]; then
              mv news-db/news.db news.db
            fi
          else
            echo "No previous run found"
          fi
          set -e
      - name: Run ingestion
        run: python ingest.py
      - name: Archive database
        uses: actions/upload-artifact@v4
        with:
          name: news-db
          path: news.db

